//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _445FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberId { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public System.DateTime MemberBirthDate { get; set; }
        public System.DateTime MembershipDate { get; set; }
        public Nullable<decimal> MemberPhoneNumber { get; set; }
        public string MemberEmail { get; set; }
        public Nullable<System.DateTime> CardPrintDate { get; set; }
    }
}
